-- New expert found while importing batch 2 of legacy appointments --
-- psychologist_id 44 (Anushka Gaur) has real bookings but was never
-- imported as an expert in the original legacy_experts_2026-07-23.sql
-- batch. status=0 in the legacy system, same convention as the other
-- inactive-but-historical psychologists already imported (Rupal Sharma,
-- Ankita Ganguly, Harshita Gurbani) -- is_bookable=false, visible on the
-- directory as a "view details" only card, not bookable.
--
-- Run this BEFORE legacy_appointments_batch2_2026-07-24.sql -- that file
-- looks her up by name via a subquery, which needs this row to already
-- exist.
insert into public.experts (name, notification_email, years_experience, bio, long_bio, languages, modalities, client_concerns, therapist_note, certifications, specialties, is_active, is_bookable) values
  ('Anushka Gaur', 'anushkamudgal@gmail.com', '2+ Years of Experience', 'Anushka Gaur is a Counselling Psychologist with a Master''s degree from IISU, Jaipur. She works with children, adolescents, and adults, supporting them through challenges like anxiety, depression, trauma, and relationship issues. Using a client-centred and compassionate approach, Anushka creates a safe space for healing, growth, and emotional well-being.', 'Anushka Gaur is a dedicated Counselling Psychologist with a Master''s degree in Counselling Psychology from IISU, Jaipur. She is deeply passionate about supporting individuals through their emotional and psychological challenges with empathy, sensitivity, and a client-centred approach. Anushka has worked with children, adolescents, and adults, helping them manage a wide range of concerns including anxiety, depression, trauma, self-esteem issues, and relationship difficulties. Her approach blends evidence-based techniques with active listening and compassion to create a safe, non-judgmental space where clients feel heard, supported, and empowered. With a focus on personal growth and emotional well-being, Anushka aims to help individuals build resilience, develop healthy coping strategies, and move forward with greater clarity and confidence. She believes in the power of therapy to transform lives and is committed to walking alongside her clients on their journey toward healing and self-discovery.', array['English','Hindi'], array['Cognitive Behavioral Therapy (CBT)','Mindfulness-Based Therapy','Emotion Regulation Strategies','Trauma-Informed Counseling','Supportive and Client-Centered Therapy'], array['I often feel overwhelmed and unable to cope','I''m stuck in negative thoughts and can''t move forward','My relationships are strained and I don''t know how to fix them','I feel lost and unsure about my purpose'], 'Anxiety, panic attacks, Depression, low mood, relationship difficulties, family conflict, stress and burnout, low self-esteem, social anxiety.', array['Counseling Psychologist'], array['individual','family-relationship'], true, false);
